{"category": "ham", "to_address": "sebastian.weber@physik.tu-darmstadt.de", "from_address": "Duncan Murdoch <murdoch@stats.uwo.ca>", "subject": "Re: [R] Bug in R 2.4.1 ?", "body": "On 4/23/2007 10:56 AM, Sebastian Weber wrote:\n> Hello everybody,\n> \n> I'm using hdf5 files to store results from intermediate calculations.\n> These are usually part of a list, called \"res\". As I want the hdf-files\n> to contain all the members of res in its top \"directory\", I used to do\n> \n> attach(res)\n> do.call(\"hdf5save\", args=c(fileout=file.path(dir, ofile),  \n>         as.list(names(res))))\n> detach(res)\n> \n> which did what I wanted (R version 2.3.1 under ubuntu edgy). Since the\n> upgrade to ubuntu feisty fawn which ships with R 2.4.1, the code above\n> causes a crash:\n> \n>  *** caught segfault ***\n> address 0x11, cause 'memory not mapped'\n> \n> Traceback:\n>  1: .External(\"do_hdf5save\", call, sys.frame(sys.parent()),\n> fileout,     ..., PACKAGE = \"hdf5\")\n>  2: hdf5save(fileout =\n> \"tex/ABpattern_pub/data/knnTest/gTest_annAB.1.statsAll.hdf5\",\n> \"newman\", \"hist\", \"graphProp\", \"graphBins\")\n>  3: do.call(\"hdf5save\", args = c(fileout = file.path(dir, ofile),\n> as.list(names(res))))\n>  4: avgGraphData(dir = \"tex/ABpattern_pub/data/knnTest\")\n> \n> Any ideas on how to fix this or what is wrong? To me it seems to be a\n> bug introduced in R 2.4.1.\n\nhdf5save is a function in the hdf5 contributed package, so you should \nstart with its maintainer, Marcus G. Daniels .  But \nbefore you bother him, make sure you're using the latest release of it. \n  If you still have problems, give him the usual details requested in\nthe posting guide.\n\nDuncan Murdoch\n\n______________________________________________\nR-help@stat.math.ethz.ch mailing list\nhttps://stat.ethz.ch/mailman/listinfo/r-help\nPLEASE do read the posting guide http://www.R-project.org/posting-guide.html\nand provide commented, minimal, self-contained, reproducible code.\n\n"}